### ISSUE TITLE
v3 API still sometimes errors on authentication over SSL

### ISSUE THREAD

**Issue by kbacha** [woothemes/wc-api-ruby#11] opened 2015-10-07 18:21 UTC
I suspect that this is a conflicting plug-in issue as passing the query params resolves it.

The error I get is:

```ruby
[32] pry(main)> api.get('products')
=> {"errors"=>[{"code"=>"woocommerce_api_authentication_error", "message"=>"Consumer Secret is invalid"}]}
```

The odd part is that the get index route works (I've tried this on the client before pull request #10 was merged). I think that the basic auth might be getting scrubbed from the request before woo even is able to process it but to that end I don't know.

It does work if I include the secret and key in the query params.

**Comment by claudiosmweb** [comment] 2015-10-07 19:23
Index works because don't need any authentication.

To V3 is not possible to pass keys as query string, I recommend you use oAuth in this case.
Maybe we can do something to force use oAuth even when the URL is over SSL.

**Comment by kbacha** [comment] 2015-10-07 19:29
Hmm, the query string is working for me on woo 2.4.7 with v3 passed into the client gem.

Will oauth work even if it's https? Should we make an option to force oauth in the gem?

**Comment by claudiosmweb** [comment] 2015-10-07 23:19
Yep, oAuth can work with https and yep, I agree have some option for it.

And sorry, I had misunderstood:
> It does work if I include the secret and key in the query params.

The problem is the server unable to configure `PHP_AUTH_USER` and `PHP_AUTH_PW`.

Here how this works: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L79-L93

See that we test for the query strings first as fallback and then we try PHP vars.

**Comment by kbacha** [comment] 2015-10-08 20:56
@claudiosmweb 

Thanks for sending me the link to the location in woocommerce code that this relates to. It looks like woo never tries to do oauth over ssl:

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L45-L49

I have a change on my fork that will allow a client to always use oauth but I don't think that will work until ssl is able to read the oauth params.

**Comment by claudiosmweb** [comment] 2015-12-07 19:49
Closing since need to use Basic Auth over SSL.

**Closed by claudiosmweb** 2015-12-07 19:49 UTC
